"""verification code

Revision ID: 189a3438e287
Revises: 337d4c684568
Create Date: 2014-01-08 01:09:38.035267

"""

# revision identifiers, used by Alembic.
revision = '189a3438e287'
down_revision = '337d4c684568'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'users', ['verification_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_column('users', 'verification_code')
    ### end Alembic commands ###
