"""indexing

Revision ID: 337d4c684568
Revises: None
Create Date: 2014-01-07 21:37:00.230916

"""

# revision identifiers, used by Alembic.
revision = '337d4c684568'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_images_title', 'images', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_title', 'images')
    ### end Alembic commands ###
