"""tags

Revision ID: 3b387b077506
Revises: 48641cbf69d7
Create Date: 2014-01-11 11:01:56.791153

"""

# revision identifiers, used by Alembic.
revision = '3b387b077506'
down_revision = '48641cbf69d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tagged_images',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], [u'images.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.id'], )
    )
    op.add_column(u'images', sa.Column('tagstring', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'images', 'tagstring')
    op.drop_table('tagged_images')
    op.drop_table('tags')
    ### end Alembic commands ###
