"""Add comments

Revision ID: 517f3420aa45
Revises: 1175c8883974
Create Date: 2014-01-14 08:31:57.919157

"""

# revision identifiers, used by Alembic.
revision = '517f3420aa45'
down_revision = '1175c8883974'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.UnicodeText(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], [u'images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    ### end Alembic commands ###
